# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ed0de2fd118419afb873c6dad825e3ed882d08036f7a664e5840e4c08e76583d66d5e59c81c9d0c45e8a78c53b56eed402042a0712c6eebcd4aa6ec86a0c417

test:
  secret_key_base: e927415ffb3deae4776112a6df0485c1076fc4e0d97e50f783eb25b446f001b24b2a02797e8bd3535031bd60193b8158ab92179fa3fc9031b0e20380a5a4782f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
